### ISSUE TITLE
error when running local development server

### ISSUE THREAD

**Issue by caseyyee** [slightlyoffbeat/mozvr#3]
```bash
/Users/casey/Developer/mozvr/next.config.js:33
    );
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadConfig (/Users/casey/Developer/mozvr/node_modules/next/dist/server/config.js:57:28)
    at getConfig (/Users/casey/Developer/mozvr/node_modules/next/dist/server/config.js:41:20)
```

**Comment by slightlyoffbeat** [comment]
Hmm. I can't reproduce. What version of node/npm are you using?

**Comment by slightlyoffbeat** [comment]
Node 8 added support for trailing commas, which is probably the issue here.

**Comment by caseyyee** [comment]
Right.  So I installed Node 8, and I'm getting a different set of errors:
```bash
npm run start

> mozilla-vr@1.0.0 start /Users/casey/Developer/mozvr
> next start

> Could not find a valid build in the '.next' directory! Try building your app with 'next build' before starting the server.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozilla-vr@1.0.0 start: `next start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mozilla-vr@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/casey/.npm/_logs/2017-08-02T18_15_39_739Z-debug.log
```

and for npm run build:

```bash
npm run build

> mozilla-vr@1.0.0 build /Users/casey/Developer/mozvr
> next build && next export -o dist

> Using external babel configuration
> location: "/Users/casey/Developer/mozvr/.babelrc"
> Using "webpack" config function defined in next.config.js.
> Failed to build on /var/folders/q7/qf31v2fx1h315y_3_gql0ks40000gn/T/35680fbb-0d70-4c87-a112-76c8b4f0d1d9
{ Error: ./styles/style.scss
Module build failed: Error: Missing binding /Users/casey/Developer/mozvr/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 7.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/casey/Developer/mozvr/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/casey/Developer/mozvr/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/casey/Developer/mozvr/node_modules/sass-loader/lib/loader.js:3:14)
 @ ./components/layout/Meta.js 19:13-47
 @ ./components/layout/Layout.js
 @ ./pages?entry
 @ multi ./pages?entry
    at /Users/casey/Developer/mozvr/node_modules/next/dist/server/build/index.js:182:21
    at emitRecords.err (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/casey/Developer/mozvr/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/casey/Developer/mozvr/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/casey/Developer/mozvr/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:360:15)
  errors: [ './styles/style.scss\nModule build failed: Error: Missing binding /Users/casey/Developer/mozvr/node_modules/node-sass/vendor/darwin-x64-57/binding.node\nNode Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x\n\nFound bindings for the following environments:\n  - OS X 64-bit with Node.js 7.x\n\nThis usually happens because your environment has changed since running `npm install`.\nRun `npm rebuild node-sass --force` to build the binding for your current environment.\n    at module.exports (/Users/casey/Developer/mozvr/node_modules/node-sass/lib/binding.js:15:13)\n    at Object.<anonymous> (/Users/casey/Developer/mozvr/node_modules/node-sass/lib/index.js:14:35)\n    at Module._compile (module.js:569:30)\n    at Object.Module._extensions..js (module.js:580:10)\n    at Module.load (module.js:503:32)\n    at tryModuleLoad (module.js:466:12)\n    at Function.Module._load (module.js:458:3)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Users/casey/Developer/mozvr/node_modules/sass-loader/lib/loader.js:3:14)\n @ ./components/layout/Meta.js 19:13-47\n @ ./components/layout/Layout.js\n @ ./pages?entry\n @ multi ./pages?entry' ],
  warnings: [] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozilla-vr@1.0.0 build: `next build && next export -o dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mozilla-vr@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/casey/.npm/_logs/2017-08-02T18_16_07_253Z-debug.log
```

**Comment by slightlyoffbeat** [comment]
That makes sense. The start script is to run the production build. Try `npm run dev` for your developer environment, or you can run `npm run build` first

**Comment by caseyyee** [comment]
OK, works now.  just needed to reinstall modules after node update.
