### ISSUE TITLE
npm run build and start broken

### ISSUE THREAD

**Issue by caseyyee** [slightlyoffbeat/mozvr#8]
will need to get this fixed so we can deploy.  `dev` seems to work fine.

```bash
npm run start

> mozilla-vr@1.0.0 start /Users/casey/Developer/mozvr
> next start

> Could not find a valid build in the '.next' directory! Try building your app with 'next build' before starting the server.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozilla-vr@1.0.0 start: `next start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mozilla-vr@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/casey/.npm/_logs/2017-08-02T18_58_16_437Z-debug.log
```

```bash
npm run build

> mozilla-vr@1.0.0 build /Users/casey/Developer/mozvr
> next build && next export -o dist

> Using external babel configuration
> location: "/Users/casey/Developer/mozvr/.babelrc"
> Using "webpack" config function defined in next.config.js.
> Failed to build on /var/folders/q7/qf31v2fx1h315y_3_gql0ks40000gn/T/e8a9c191-254f-4f96-b82e-11e9b2df2ea0
{ Error: ./styles/style.scss
Module build failed: Error: UnCSS: no HTML files found
    at getHTML (/Users/casey/Developer/mozvr/node_modules/uncss/src/uncss.js:32:31)
    at process (/Users/casey/Developer/mozvr/node_modules/uncss/src/uncss.js:223:20)
    at /Users/casey/Developer/mozvr/node_modules/uncss/src/uncss.js:249:16
    at LazyResult.run (/Users/casey/Developer/mozvr/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.asyncTick (/Users/casey/Developer/mozvr/node_modules/postcss/lib/lazy-result.js:185:32)
    at LazyResult.asyncTick (/Users/casey/Developer/mozvr/node_modules/postcss/lib/lazy-result.js:197:22)
    at /Users/casey/Developer/mozvr/node_modules/postcss/lib/lazy-result.js:190:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./components/layout/Meta.js 19:13-47
 @ ./components/layout/Layout.js
 @ ./pages?entry
 @ multi ./pages?entry
    at /Users/casey/Developer/mozvr/node_modules/next/dist/server/build/index.js:182:21
    at emitRecords.err (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/casey/Developer/mozvr/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/casey/Developer/mozvr/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/casey/Developer/mozvr/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/casey/Developer/mozvr/node_modules/webpack/lib/Compiler.js:360:15)
    at /Users/casey/Developer/mozvr/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/casey/Developer/mozvr/node_modules/async/dist/async.js:998:13)
    at /Users/casey/Developer/mozvr/node_modules/async/dist/async.js:906:16
    at /Users/casey/Developer/mozvr/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
  errors: [ './styles/style.scss\nModule build failed: Error: UnCSS: no HTML files found\n    at getHTML (/Users/casey/Developer/mozvr/node_modules/uncss/src/uncss.js:32:31)\n    at process (/Users/casey/Developer/mozvr/node_modules/uncss/src/uncss.js:223:20)\n    at /Users/casey/Developer/mozvr/node_modules/uncss/src/uncss.js:249:16\n    at LazyResult.run (/Users/casey/Developer/mozvr/node_modules/postcss/lib/lazy-result.js:270:20)\n    at LazyResult.asyncTick (/Users/casey/Developer/mozvr/node_modules/postcss/lib/lazy-result.js:185:32)\n    at LazyResult.asyncTick (/Users/casey/Developer/mozvr/node_modules/postcss/lib/lazy-result.js:197:22)\n    at /Users/casey/Developer/mozvr/node_modules/postcss/lib/lazy-result.js:190:27\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)\n @ ./components/layout/Meta.js 19:13-47\n @ ./components/layout/Layout.js\n @ ./pages?entry\n @ multi ./pages?entry' ],
  warnings: [] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozilla-vr@1.0.0 build: `next build && next export -o dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mozilla-vr@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/casey/.npm/_logs/2017-08-02T18_58_43_662Z-debug.log
```

**Comment by slightlyoffbeat** [comment]
Looks like an issue when using uncss on a fresh install. I may just remove uncss for now.

**Comment by slightlyoffbeat** [comment]
Fixed for now. We can revisit how to remove unused CSS in the future.
